
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRING_LITERAL = 11;
  public static final int DIGIT = 10;
  public static final int EOF = 0;
  public static final int PLUS = 7;
  public static final int ARROW = 9;
  public static final int NUMERO = 4;
  public static final int error = 1;
  public static final int SEMICOLON = 8;
  public static final int IDENTIFIER = 12;
  public static final int SIMBOLO = 5;
  public static final int SENHA = 6;
  public static final int MAIUSCULA = 2;
  public static final int MINUSCULA = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAIUSCULA",
  "MINUSCULA",
  "NUMERO",
  "SIMBOLO",
  "SENHA",
  "PLUS",
  "SEMICOLON",
  "ARROW",
  "DIGIT",
  "STRING_LITERAL",
  "IDENTIFIER"
  };
}

