
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS_SPEED = 84;
  public static final int MINUS_DUCK = 88;
  public static final int CL_CROSSHAIRALPHA = 28;
  public static final int CL_CROSSHAIRSIZE = 24;
  public static final int SND_SPATIALIZE_LERP = 38;
  public static final int CL_CROSSHAIR_SNIPER_WIDTH = 34;
  public static final int MINUS_ATTACK2 = 92;
  public static final int CL_CROSSHAIR_DRAWOUTLINE = 21;
  public static final int TOGGLE = 112;
  public static final int CL_RADAR_SQUARE_WITH_SCOREBOARD = 10;
  public static final int CL_CROSSHAIR_OUTLINETHICKNESS = 22;
  public static final int SKEY = 114;
  public static final int SND_DEATHCAMERA_VOLUME = 46;
  public static final int CL_SCOREBOARD_MOUSE_ENABLE_BINDING = 65;
  public static final int CL_RADAR_ROTATE = 15;
  public static final int CL_CROSSHAIRDOT = 27;
  public static final int CL_HUD_COLOR = 7;
  public static final int RBRACE = 120;
  public static final int PLUS_ATTACK2 = 91;
  public static final int MINUS_LEFT = 80;
  public static final int MINUS_FORWARD = 76;
  public static final int SND_MUTE_MVP_MUSIC_LIVE_PLAYERS = 40;
  public static final int PLUS_JUMP = 85;
  public static final int CLEAR = 73;
  public static final int HOST_WRITECONFIG = 72;
  public static final int SND_ROUNDACTION_VOLUME = 44;
  public static final int MINUS_SCORE = 98;
  public static final int LBRACE = 119;
  public static final int R_PLAYER_VISIBILITY_MODE = 58;
  public static final int ZOOM_SENSITIVITY_RATIO = 51;
  public static final int PLUS_BACK = 77;
  public static final int SND_HEADPHONE_EQ = 37;
  public static final int CL_COLOR = 6;
  public static final int CL_USE_OPENS_BUY_MENU = 59;
  public static final int ERROR = 121;
  public static final int MINUS_ATTACK = 90;
  public static final int PLUS_FORWARD = 75;
  public static final int CL_SHOWLOADOUT = 9;
  public static final int PLUS_SPEED = 83;
  public static final int CL_CROSSHAIRGAP_USEWEAPONVALUE = 33;
  public static final int SND_MIXAHEAD = 36;
  public static final int CL_TEAMID_OVERHEAD_COLORS_SHOW = 61;
  public static final int FPS_MAX = 3;
  public static final int SPEC_SHOW_XRAY = 67;
  public static final int JOYSTICK = 69;
  public static final int CL_CROSSHAIRGAP = 26;
  public static final int MM_DEDICATED_SEARCH_MAXPING = 55;
  public static final int CL_SNIPER_DELAY_UNSCOPE = 52;
  public static final int PLUS_USE = 95;
  public static final int MINUS_RIGHT = 82;
  public static final int CL_CROSSHAIRCOLOR_R = 32;
  public static final int SND_ROUNDEND_VOLUME = 43;
  public static final int BIND = 70;
  public static final int NUMBER = 115;
  public static final int PROFILE = 117;
  public static final int CL_CROSSHAIRCOLOR_G = 31;
  public static final int ALIAS = 71;
  public static final int HUD_SHOWTARGETID = 5;
  public static final int CL_CROSSHAIRCOLOR_B = 30;
  public static final int CL_TEAMMATE_COLORS_SHOW = 62;
  public static final int SND_STEAMAUDIO_ENABLE_PERSPECTIVE_CORRECTION = 39;
  public static final int CL_CROSSHAIR_RECOIL = 35;
  public static final int MINUS_RELOAD = 94;
  public static final int MINUS_JUMP = 86;
  public static final int PLUS_SCORE = 97;
  public static final int VIEWMODEL_FOV = 17;
  public static final int PLUS_ATTACK = 89;
  public static final int MINUS_BACK = 78;
  public static final int ECHO = 74;
  public static final int R_FULLSCREEN_GAMMA = 2;
  public static final int HUD_SCALING = 4;
  public static final int CL_CROSSHAIRCOLOR = 29;
  public static final int CL_HUD_RADAR_SCALE = 12;
  public static final int SND_VOIPVOLUME = 47;
  public static final int SEMICOLON = 118;
  public static final int EOF = 0;
  public static final int CL_ALLOW_ANIMATED_AVATARS = 8;
  public static final int R_SHOW_BUILD_INFO = 11;
  public static final int CL_JOIN_ADVERTISE = 64;
  public static final int TOGGLECONSOLE = 111;
  public static final int SND_ROUNDSTART_VOLUME = 42;
  public static final int PLUS_RIGHT = 81;
  public static final int CL_SILENCER_MODE = 66;
  public static final int PLUS_DUCK = 87;
  public static final int SND_TENSECONDWARNING_VOLUME = 48;
  public static final int CL_DM_BUYRANDOMWEAPONS = 63;
  public static final int BATTERY_SAVER = 68;
  public static final int SENSITIVITY = 50;
  public static final int SND_MVP_VOLUME = 45;
  public static final int error = 1;
  public static final int SND_MENUMUSIC_VOLUME = 41;
  public static final int PLUS_VOICERECORD = 99;
  public static final int PLUS_RELOAD = 93;
  public static final int CL_CROSSHAIRTHICKNESS = 25;
  public static final int ID = 113;
  public static final int VIEWMODEL_PRESETPOS = 16;
  public static final int SLOT10 = 110;
  public static final int CL_TEAMID_OVERHEAD_MODE = 60;
  public static final int CL_RADAR_SCALE = 13;
  public static final int CL_RADAR_ALWAYS_CENTERED = 14;
  public static final int PLUS_LEFT = 79;
  public static final int CL_CROSSHAIRSTYLE = 23;
  public static final int MINUS_USE = 96;
  public static final int VIEWMODEL_OFFSET_Z = 20;
  public static final int VIEWMODEL_OFFSET_Y = 19;
  public static final int VIEWMODEL_OFFSET_X = 18;
  public static final int STRING = 116;
  public static final int SLOT9 = 109;
  public static final int SLOT8 = 108;
  public static final int SLOT7 = 107;
  public static final int SLOT6 = 106;
  public static final int SLOT5 = 105;
  public static final int SLOT4 = 104;
  public static final int SLOT3 = 103;
  public static final int VOLUME = 49;
  public static final int SLOT2 = 102;
  public static final int CON_ENABLE = 54;
  public static final int SLOT1 = 101;
  public static final int CL_SNIPER_AUTO_REZOOM = 53;
  public static final int UI_STEAM_OVERLAY_NOTIFICATION_POSITION = 56;
  public static final int MINUS_VOICERECORD = 100;
  public static final int ENGINE_LOW_LATENCY_SLEEP_AFTER_CLIENT_TICK = 57;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "R_FULLSCREEN_GAMMA",
  "FPS_MAX",
  "HUD_SCALING",
  "HUD_SHOWTARGETID",
  "CL_COLOR",
  "CL_HUD_COLOR",
  "CL_ALLOW_ANIMATED_AVATARS",
  "CL_SHOWLOADOUT",
  "CL_RADAR_SQUARE_WITH_SCOREBOARD",
  "R_SHOW_BUILD_INFO",
  "CL_HUD_RADAR_SCALE",
  "CL_RADAR_SCALE",
  "CL_RADAR_ALWAYS_CENTERED",
  "CL_RADAR_ROTATE",
  "VIEWMODEL_PRESETPOS",
  "VIEWMODEL_FOV",
  "VIEWMODEL_OFFSET_X",
  "VIEWMODEL_OFFSET_Y",
  "VIEWMODEL_OFFSET_Z",
  "CL_CROSSHAIR_DRAWOUTLINE",
  "CL_CROSSHAIR_OUTLINETHICKNESS",
  "CL_CROSSHAIRSTYLE",
  "CL_CROSSHAIRSIZE",
  "CL_CROSSHAIRTHICKNESS",
  "CL_CROSSHAIRGAP",
  "CL_CROSSHAIRDOT",
  "CL_CROSSHAIRALPHA",
  "CL_CROSSHAIRCOLOR",
  "CL_CROSSHAIRCOLOR_B",
  "CL_CROSSHAIRCOLOR_G",
  "CL_CROSSHAIRCOLOR_R",
  "CL_CROSSHAIRGAP_USEWEAPONVALUE",
  "CL_CROSSHAIR_SNIPER_WIDTH",
  "CL_CROSSHAIR_RECOIL",
  "SND_MIXAHEAD",
  "SND_HEADPHONE_EQ",
  "SND_SPATIALIZE_LERP",
  "SND_STEAMAUDIO_ENABLE_PERSPECTIVE_CORRECTION",
  "SND_MUTE_MVP_MUSIC_LIVE_PLAYERS",
  "SND_MENUMUSIC_VOLUME",
  "SND_ROUNDSTART_VOLUME",
  "SND_ROUNDEND_VOLUME",
  "SND_ROUNDACTION_VOLUME",
  "SND_MVP_VOLUME",
  "SND_DEATHCAMERA_VOLUME",
  "SND_VOIPVOLUME",
  "SND_TENSECONDWARNING_VOLUME",
  "VOLUME",
  "SENSITIVITY",
  "ZOOM_SENSITIVITY_RATIO",
  "CL_SNIPER_DELAY_UNSCOPE",
  "CL_SNIPER_AUTO_REZOOM",
  "CON_ENABLE",
  "MM_DEDICATED_SEARCH_MAXPING",
  "UI_STEAM_OVERLAY_NOTIFICATION_POSITION",
  "ENGINE_LOW_LATENCY_SLEEP_AFTER_CLIENT_TICK",
  "R_PLAYER_VISIBILITY_MODE",
  "CL_USE_OPENS_BUY_MENU",
  "CL_TEAMID_OVERHEAD_MODE",
  "CL_TEAMID_OVERHEAD_COLORS_SHOW",
  "CL_TEAMMATE_COLORS_SHOW",
  "CL_DM_BUYRANDOMWEAPONS",
  "CL_JOIN_ADVERTISE",
  "CL_SCOREBOARD_MOUSE_ENABLE_BINDING",
  "CL_SILENCER_MODE",
  "SPEC_SHOW_XRAY",
  "BATTERY_SAVER",
  "JOYSTICK",
  "BIND",
  "ALIAS",
  "HOST_WRITECONFIG",
  "CLEAR",
  "ECHO",
  "PLUS_FORWARD",
  "MINUS_FORWARD",
  "PLUS_BACK",
  "MINUS_BACK",
  "PLUS_LEFT",
  "MINUS_LEFT",
  "PLUS_RIGHT",
  "MINUS_RIGHT",
  "PLUS_SPEED",
  "MINUS_SPEED",
  "PLUS_JUMP",
  "MINUS_JUMP",
  "PLUS_DUCK",
  "MINUS_DUCK",
  "PLUS_ATTACK",
  "MINUS_ATTACK",
  "PLUS_ATTACK2",
  "MINUS_ATTACK2",
  "PLUS_RELOAD",
  "MINUS_RELOAD",
  "PLUS_USE",
  "MINUS_USE",
  "PLUS_SCORE",
  "MINUS_SCORE",
  "PLUS_VOICERECORD",
  "MINUS_VOICERECORD",
  "SLOT1",
  "SLOT2",
  "SLOT3",
  "SLOT4",
  "SLOT5",
  "SLOT6",
  "SLOT7",
  "SLOT8",
  "SLOT9",
  "SLOT10",
  "TOGGLECONSOLE",
  "TOGGLE",
  "ID",
  "SKEY",
  "NUMBER",
  "STRING",
  "PROFILE",
  "SEMICOLON",
  "LBRACE",
  "RBRACE",
  "ERROR"
  };
}

